kind: pipeline
name: default


steps:

- name: testing
  image: golang
  commands:
  - go build
  - go test

- name: docker  
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKER_USER
    password:
      from_secret: DOCKER_PASS
    repo: macintoshprime/hello-kubernetes
    tags: latest
    dockerfile: build/Dockerfile