stages:
  - validate
  - conformance
  - build

validate:
  stage: validate
  image:
    name: garethr/kubeval
    entrypoint:
      - ""
  script:
    - kubeval --strict deploy/*

conformance:
  stage: conformance
  image:
    name: instrumenta/conftest:latest
    entrypoint:
      - ""
  script:
    - conftest test "deploy/*"

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - ls
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $(pwd) --dockerfile build/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
