apiVersion:  autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: hello
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 40
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kube
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: hello
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: macintoshprime/hello-kubernetes:v8
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
