apiVersion:  autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: hello
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40